site_name: input4MIPs Controlled Vocabularies (CVs)
site_description: Controlled Vocabularies (CVs) for use in input4MIPs
site_url: https://input4mips-cvs.readthedocs.io/
edit_uri: blob/main/docs/

repo_name: PCMDI/input4MIPs_CVs
repo_url: https://github.com/PCMDI/input4MIPs_CVs

nav:
  - input4MIPs CVs: index.md
  - Usage:
    - As a data user: 
      - Overview: usage-data-user/index.md
      - Downloading data: usage-data-user/downloading.md
    - As a data producer: usage-data-producer.md
  - Dataset overviews:
    - Summary: dataset-overviews/index.md
    - Anthropogenic short-lived climate forcer (SLCF) and CO<sub>2</sub> emissions: dataset-overviews/anthropogenic-slcf-co2-emissions.md
    - Open biomass burning emissions: dataset-overviews/open-biomass-burning-emissions.md
    - Land use: dataset-overviews/land-use.md
    - Greenhouse gas concentrations: dataset-overviews/greenhouse-gas-concentrations.md
    - CO<sub>2</sub> isotopes: dataset-overviews/co2-isotopes.md
    - Stratospheric volcanic SO<sub>2</sub> emissions and aerosol optical properties: dataset-overviews/stratospheric-volcanic-so2-emissions-aod.md
    - Ozone concentrations: dataset-overviews/ozone.md
    - Nitrogen deposition: dataset-overviews/nitrogen-deposition.md
    - Solar: dataset-overviews/solar.md
    - AMIP sea-surface temperature and sea-ice boundary forcing: dataset-overviews/amip-sst-sea-ice-boundary-forcing.md
    - Aerosol optical properties/MACv2-SP: dataset-overviews/aerosol-optical-properties-macv2-sp.md
    - Population density: dataset-overviews/population.md
  - Database views:
    - Overview: database-views/index.md
    - Delivery summary: database-views/input4MIPs_delivery-summary.html
    - Delivery summary ScenarioMIP: database-views/input4MIPs_delivery-summary-scenariomip.html
    - Source ID-level CMIP7: database-views/input4MIPs_source-id_CMIP7.html
    - Dataset-level CMIP7: database-views/input4MIPs_datasets_CMIP7.html
    - File-level CMIP7: database-views/input4MIPs_files_CMIP7.html
    - Source ID-level CMIP6Plus: database-views/input4MIPs_source-id_CMIP6Plus.html
    - Dataset-level CMIP6Plus: database-views/input4MIPs_datasets_CMIP6Plus.html
    - File-level CMIP6Plus: database-views/input4MIPs_files_CMIP6Plus.html
    - Source ID-level CMIP7Plus: database-views/input4MIPs_source-id_CMIP7Plus.html
    - Dataset-level CMIP7Plus: database-views/input4MIPs_datasets_CMIP7Plus.html
    - File-level CMIP7Plus: database-views/input4MIPs_files_CMIP7Plus.html
  - Extracting scenario from source ID: extracting-scenario-from-source-id.md
  - Source ID landing pages: source-id-landing-pages/
  - Repository overview: repository-overview.md
  - Contributing: contributing.md
  - Versioning: versioning.md
  - Changelog: changelog.md

theme:
  name: "material"
  features:
    - content.code.copy
  palette:
    # Light mode (toggle to dark mode)
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode (toggle back to light mode)
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: UA-3843414-4

plugins:
  - search
  - autorefs
  # Required for auto-filling the revision history
  # https://oprypin.github.io/mkdocs-gen-files/
  - gen-files:
      scripts:
        - docs/dataset-overviews/fill-out-auto-generated-sections.py
        - docs/source-id-landing-pages/auto-generate-source-id-pages.py
  # Required for handling the source ID landing pages
  - literate-nav:


markdown_extensions:
  - attr_list
  - footnotes
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex-mkdocsyml
  - pymdownx.arithmatex:
      generic: true
  # Code highlighting handiness
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # Ensure that there are links to table of contents items
  - toc:
      permalink: "#"

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

watch:
  - README.md
