name: Continuous integration (CI)

on: 
  pull_request:

jobs:
  check-database-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check database up to date
        run: |
          which pip
          pip install python-packages/input4MIPs-CVs
          python python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py --repo-root-dir . || (echo 'Database entries not up to date with inputs. Please run `python python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py --repo-root-dir .` or the equivalent for your machine.' && exit 1)
