name: Release

on:
  workflow_dispatch:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/release_template.md"
          draft: true
          files: |
            CVs/*
