name: Release

on:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate Release Notes
        run: |
          echo "" >> ".github/release_template.md"
          echo "## Changelog" >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          pip install typer
          python scripts/changelog-to-release-template.py >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          echo "## Changes" >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty='format:* %h %s' --no-merges >> ".github/release_template.md"

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".github/release_template.md"
          draft: true
          files: |
            CVs/*
